name: Infuse
version: 1.0.0
main: com.infuse.spark.InfuseSparkPlugin
api-version: '1.21'
commands:
  infusespark:
    description: Manage Infuse spark selection.
    permission: infuse.command.infusespark
    usage: /<command> equip <primary|support> <type>
  infuse:
    description: Infuse settings and abilities.
    usage: /<command> settings|ability|trust
  pdrain:
    description: Drain the current primary spark.
  sdrain:
    description: Drain the current support spark.
permissions:
  infuse.command.infusespark:
    description: Allows use of /infusespark.
    default: op
