name: Infuse
version: 1.0.0
main: com.infuse.spark.InfuseSparkPlugin
api-version: '1.21'
commands:
  infuse:
    description: Infuse settings, abilities, and spark selection.
    usage: /<command> spark|settings|ability|trust|primary|support
  drain:
    description: Drain the current infuse slot.
    usage: /<command> <1|2>
  infuses:
    description: View all available infuses.
    usage: /<command>
permissions:
  infuse.command.infusespark:
    description: Allows use of /infuse spark.
    default: op
  infuse.admin:
    description: Allows use of /infuse reload.
    default: op
