name: Infuse
version: 1.0.0
main: com.infuse.spark.InfuseSparkPlugin
api-version: '1.21'
commands:
  infuse:
    description: Infuse settings, abilities, and spark selection.
    usage: /<command> spark|settings|ability|trust|primary|support
  drain:
    description: Drain the current primary or support spark.
    usage: /<command> <1|2>
permissions:
  infuse.command.infusespark:
    description: Allows use of /infuse spark.
    default: op
